services:
  database:
    container_name: template.database
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw

    ports:
      - "${POSTGRES_PORT}:5432"

    command: postgres -c 'max_connections=${POSTGRES_MAX_CONNECTIONS:-100}'
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    env_file:
      - .env


  redis:
    container_name: template.redis
    image: redis:latest

    ports:
      - "${REDIS_PORT}:6379"

    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  postgres_data:
    name: postgres_data
